name: Deploy

on:
  deployment

jobs:
  deploy:
    name: Deploy ${{ github.event.deployment.environment }} ${{ github.event.deployment.ref }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Publish
        run: ruby -e 'puts "Deploy"'
